name: langchain-aws-service
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - aws-cdk-lib
    - langchain
    - boto3
    - requests
    - streamlit
